# Generated by Django 3.0.5 on 2020-04-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='author_email',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='testmodel',
            name='publish_date',
        ),
    ]
