# Generated by Django 3.0.5 on 2020-04-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_testmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
